language: python
python:
  - "2.7"
dist: trusty
addons:
  chrome: stable
install:
  - sudo curl --output /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
  - sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
install:
- pip install -r dev-requirements.txt
script:
- nose2
